[program:kiani_user_bot]
command=%(ENV_HOME)s/telegram_bot_repo/kiani-exchange/backend/venv/bin/python bots/user_bot.py
directory=%(ENV_HOME)s/telegram_bot_repo/kiani-exchange/backend
user=kianirad2020
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/kiani_user_bot.out.log
stderr_logfile=/var/log/kiani_user_bot.err.log
