[program:kiani_miniapp]
command=/usr/bin/npm run dev -- --host 0.0.0.0 --port 5173
directory=%(ENV_HOME)s/telegram_bot_repo/kiani-exchange/frontend/mini-app
user=kianirad2020
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/kiani_miniapp.out.log
stderr_logfile=/var/log/kiani_miniapp.err.log
environment=NODE_ENV="development"
