[program:kiani_api]
command=%(ENV_HOME)s/telegram_bot_repo/kiani-exchange/backend/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000
directory=%(ENV_HOME)s/telegram_bot_repo/kiani-exchange/backend
user=kianirad2020
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/kiani_api.out.log
stderr_logfile=/var/log/kiani_api.err.log
environment=PATH="%(ENV_HOME)s/telegram_bot_repo/kiani-exchange/backend/venv/bin"
