[program:kiani_adminpanel]
command=/usr/bin/npm run dev -- --host 0.0.0.0 --port 5174
directory=%(ENV_HOME)s/telegram_bot_repo/kiani-exchange/frontend/admin-panel
user=kianirad2020
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/kiani_adminpanel.out.log
stderr_logfile=/var/log/kiani_adminpanel.err.log
environment=NODE_ENV="development"
