[program:kiani_admin_bot]
command=%(ENV_HOME)s/telegram_bot_repo/kiani-exchange/backend/venv/bin/python bots/admin_bot.py
directory=%(ENV_HOME)s/telegram_bot_repo/kiani-exchange/backend
user=kianirad2020
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/kiani_admin_bot.out.log
stderr_logfile=/var/log/kiani_admin_bot.err.log
